regions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.LocalityView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.LocalityView.as_view(), name='locality'),
    url(r'^create_new$', views.LocalityCreate.as_view(), name='locality_create'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.LocalityUpdate.as_view(), name='locality_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.LocalityDelete.as_view(), name='locality_delete'),
]

test_task/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^regions/', include('regions.urls', namespace="regions")),
    url(r'^admin/', include(admin.site.urls)),
]

regions/models.py
# This is an auto-generated Django model module.

from django.db import models


# This class uses to create table in database and work with this table
class Locality(models.Model):

    title = models.CharField(max_length=255)
    abbreviations = models.CharField(max_length=3, blank=True, null=True)
    parent_id = models.IntegerField(blank=True, null=True)
    number = models.IntegerField(blank=True, null=True)
    locality_type = models.CharField(max_length=24, blank=True, null=True)

    # This class uses to change standard name to "locality"
    class Meta:
        db_table = 'locality'

    def __str__(self):
        return self.title

regions/views.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.views import generic
from django.core.urlresolvers import reverse_lazy

from .models import Locality


# This class uses to show list of locality
class LocalityView(generic.ListView):
    template_name = 'regions/index.html'
    context_object_name = 'regions_list'

    def get_queryset(self, **kwargs):
        if self.kwargs:
            return Locality.objects.filter(parent_id=self.kwargs['pk'])
        else:
            return Locality.objects.filter(parent_id=None)


# This class uses to create new locality
class LocalityCreate(generic.CreateView):
    model = Locality
    success_url = reverse_lazy('regions:index')
    fields = ['title', 'abbreviations', 'parent_id', 'number', 'locality_type']

    # This decorator and functionto give permission only for admin
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(LocalityCreate, self).dispatch(*args, **kwargs)


# This class uses to change locality
class LocalityUpdate(generic.UpdateView):
    model = Locality
    template_name_suffix = '_form'
    success_url = reverse_lazy('regions:index')
    fields = ['title', 'abbreviations', 'parent_id', 'number', 'locality_type']
    
    # This decorator and functionto give permission only for admin
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(LocalityUpdate, self).dispatch(*args, **kwargs)


# This class uses to delete locality
class LocalityDelete(generic.DeleteView):
    model = Locality
    template_name = 'regions/locality_delete.html'
    success_url = reverse_lazy('regions:index')
    
    # This decorator and functionto give permission only for admin
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(LocalityDelete, self).dispatch(*args, **kwargs)

regions/templates/regions/index.html
<!-- Templates to show list of localities -->
{% if regions_list %}
    <ul>
    
    {% for region in regions_list %}
        {# 'if' takes localities what are cities or villages  #}
        {% if region.number and region.parent_id %}
            <li>
                {{ region.title }} {{region.locality_type}}
                {% if request.user.is_superuser %}
                <a href="{% url 'regions:locality_update' region.id %}">Edit</a>
                <a href="{% url 'regions:locality_delete' region.id %}">Delete</a>
                {% endif %}
            </li>
        {% else %}
            <li>
                <a href="{% url 'regions:locality' region.id %}">{{ region.title }} {{region.locality_type}}</a>
                {% if request.user.is_superuser %}
                <a href="{% url 'regions:locality_update' region.id %}">Edit</a>
                <a href="{% url 'regions:locality_delete' region.id %}">Delete</a>
                {% endif %}
            </li>
        {% endif %}

    {% endfor %}
    </ul>
    {% if request.user.is_superuser %}
        <h3><a href="{% url 'regions:locality_create' %}">Add new locality</a></h3>
    {% endif %}
{% else %}
    <p>No regions are available.</p>
{% endif %}

regions/templates/regions/locality_delete.html
<!-- Template to delete locality -->
<form method="post">
     {% csrf_token %}
    <p>Are you sure you want to delete {{ object.title }}?</p>
    <input type="submit" value="yes" />
</form>

<button>
    <a href="{% url 'regions:index' %}" style="text-decoration: none">no</a>
</button>

regions/templates/regions/locality_form.html
<!-- Template to create or change locality -->
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Continue" />
</form>